//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM 關聯性中繼資料

[assembly: EdmRelationshipAttribute("BroadcastModel", "FK_tblSchedule_tblRecordSound", "tblRecordSound", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(wpfBroadcast.tblRecordSound), "tblSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(wpfBroadcast.tblSchedule), true)]

#endregion

namespace wpfBroadcast
{
    #region 內容
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    public partial class BroadcastEntities : ObjectContext
    {
        #region 建構函式
    
        /// <summary>
        /// 使用在應用程式組態檔的 'BroadcastEntities' 區段中找到的連接字串，初始化新的 BroadcastEntities 物件。
        /// </summary>
        public BroadcastEntities() : base("name=BroadcastEntities", "BroadcastEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 BroadcastEntities 物件。
        /// </summary>
        public BroadcastEntities(string connectionString) : base(connectionString, "BroadcastEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 BroadcastEntities 物件。
        /// </summary>
        public BroadcastEntities(EntityConnection connection) : base(connection, "BroadcastEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 部分方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblUser> tblUser
        {
            get
            {
                if ((_tblUser == null))
                {
                    _tblUser = base.CreateObjectSet<tblUser>("tblUser");
                }
                return _tblUser;
            }
        }
        private ObjectSet<tblUser> _tblUser;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblUserGroup> tblUserGroup
        {
            get
            {
                if ((_tblUserGroup == null))
                {
                    _tblUserGroup = base.CreateObjectSet<tblUserGroup>("tblUserGroup");
                }
                return _tblUserGroup;
            }
        }
        private ObjectSet<tblUserGroup> _tblUserGroup;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblSIte> tblSIte
        {
            get
            {
                if ((_tblSIte == null))
                {
                    _tblSIte = base.CreateObjectSet<tblSIte>("tblSIte");
                }
                return _tblSIte;
            }
        }
        private ObjectSet<tblSIte> _tblSIte;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblSysLog> tblSysLog
        {
            get
            {
                if ((_tblSysLog == null))
                {
                    _tblSysLog = base.CreateObjectSet<tblSysLog>("tblSysLog");
                }
                return _tblSysLog;
            }
        }
        private ObjectSet<tblSysLog> _tblSysLog;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblSchedule> tblSchedule
        {
            get
            {
                if ((_tblSchedule == null))
                {
                    _tblSchedule = base.CreateObjectSet<tblSchedule>("tblSchedule");
                }
                return _tblSchedule;
            }
        }
        private ObjectSet<tblSchedule> _tblSchedule;
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        public ObjectSet<tblRecordSound> tblRecordSound
        {
            get
            {
                if ((_tblRecordSound == null))
                {
                    _tblRecordSound = base.CreateObjectSet<tblRecordSound>("tblRecordSound");
                }
                return _tblRecordSound;
            }
        }
        private ObjectSet<tblRecordSound> _tblRecordSound;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 將新物件加入 tblUser EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblUser(tblUser tblUser)
        {
            base.AddObject("tblUser", tblUser);
        }
    
        /// <summary>
        /// 將新物件加入 tblUserGroup EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblUserGroup(tblUserGroup tblUserGroup)
        {
            base.AddObject("tblUserGroup", tblUserGroup);
        }
    
        /// <summary>
        /// 將新物件加入 tblSIte EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblSIte(tblSIte tblSIte)
        {
            base.AddObject("tblSIte", tblSIte);
        }
    
        /// <summary>
        /// 將新物件加入 tblSysLog EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblSysLog(tblSysLog tblSysLog)
        {
            base.AddObject("tblSysLog", tblSysLog);
        }
    
        /// <summary>
        /// 將新物件加入 tblSchedule EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblSchedule(tblSchedule tblSchedule)
        {
            base.AddObject("tblSchedule", tblSchedule);
        }
    
        /// <summary>
        /// 將新物件加入 tblRecordSound EntitySet 的方法已被取代。請考慮改為使用關聯的 ObjectSet&lt;T&gt; 屬性的 .Add 方法。
        /// </summary>
        public void AddTotblRecordSound(tblRecordSound tblRecordSound)
        {
            base.AddObject("tblRecordSound", tblRecordSound);
        }

        #endregion

    }

    #endregion

    #region 實體
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BroadcastModel", Name="tblRecordSound")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblRecordSound : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblRecordSound 物件。
        /// </summary>
        /// <param name="playIndex">PlayIndex 屬性的初始值。</param>
        /// <param name="name">Name 屬性的初始值。</param>
        public static tblRecordSound CreatetblRecordSound(global::System.Int32 playIndex, global::System.String name)
        {
            tblRecordSound tblRecordSound = new tblRecordSound();
            tblRecordSound.PlayIndex = playIndex;
            tblRecordSound.Name = name;
            return tblRecordSound;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayIndex
        {
            get
            {
                return _PlayIndex;
            }
            set
            {
                if (_PlayIndex != value)
                {
                    OnPlayIndexChanging(value);
                    ReportPropertyChanging("PlayIndex");
                    _PlayIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PlayIndex");
                    OnPlayIndexChanged();
                }
            }
        }
        private global::System.Int32 _PlayIndex;
        partial void OnPlayIndexChanging(global::System.Int32 value);
        partial void OnPlayIndexChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BroadcastModel", "FK_tblSchedule_tblRecordSound", "tblSchedule")]
        public EntityCollection<tblSchedule> tblSchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tblSchedule>("BroadcastModel.FK_tblSchedule_tblRecordSound", "tblSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tblSchedule>("BroadcastModel.FK_tblSchedule_tblRecordSound", "tblSchedule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BroadcastModel", Name="tblSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSchedule : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblSchedule 物件。
        /// </summary>
        /// <param name="timeStamp">TimeStamp 屬性的初始值。</param>
        /// <param name="playIndex">PlayIndex 屬性的初始值。</param>
        /// <param name="isMute">IsMute 屬性的初始值。</param>
        public static tblSchedule CreatetblSchedule(global::System.DateTime timeStamp, global::System.Int32 playIndex, global::System.Boolean isMute)
        {
            tblSchedule tblSchedule = new tblSchedule();
            tblSchedule.TimeStamp = timeStamp;
            tblSchedule.PlayIndex = playIndex;
            tblSchedule.IsMute = isMute;
            return tblSchedule;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                if (_TimeStamp != value)
                {
                    OnTimeStampChanging(value);
                    ReportPropertyChanging("TimeStamp");
                    _TimeStamp = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TimeStamp");
                    OnTimeStampChanged();
                }
            }
        }
        private global::System.DateTime _TimeStamp;
        partial void OnTimeStampChanging(global::System.DateTime value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PlayIndex
        {
            get
            {
                return _PlayIndex;
            }
            set
            {
                OnPlayIndexChanging(value);
                ReportPropertyChanging("PlayIndex");
                _PlayIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlayIndex");
                OnPlayIndexChanged();
            }
        }
        private global::System.Int32 _PlayIndex;
        partial void OnPlayIndexChanging(global::System.Int32 value);
        partial void OnPlayIndexChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsMute
        {
            get
            {
                return _IsMute;
            }
            set
            {
                OnIsMuteChanging(value);
                ReportPropertyChanging("IsMute");
                _IsMute = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsMute");
                OnIsMuteChanged();
            }
        }
        private global::System.Boolean _IsMute;
        partial void OnIsMuteChanging(global::System.Boolean value);
        partial void OnIsMuteChanged();

        #endregion

    
        #region 導覽屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BroadcastModel", "FK_tblSchedule_tblRecordSound", "tblRecordSound")]
        public tblRecordSound tblRecordSound
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRecordSound>("BroadcastModel.FK_tblSchedule_tblRecordSound", "tblRecordSound").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRecordSound>("BroadcastModel.FK_tblSchedule_tblRecordSound", "tblRecordSound").Value = value;
            }
        }
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tblRecordSound> tblRecordSoundReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tblRecordSound>("BroadcastModel.FK_tblSchedule_tblRecordSound", "tblRecordSound");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tblRecordSound>("BroadcastModel.FK_tblSchedule_tblRecordSound", "tblRecordSound", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BroadcastModel", Name="tblSIte")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSIte : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblSIte 物件。
        /// </summary>
        /// <param name="sITE_ID">SITE_ID 屬性的初始值。</param>
        /// <param name="comm">Comm 屬性的初始值。</param>
        /// <param name="aC">AC 屬性的初始值。</param>
        /// <param name="dC">DC 屬性的初始值。</param>
        /// <param name="amp">Amp 屬性的初始值。</param>
        /// <param name="speaker">Speaker 屬性的初始值。</param>
        /// <param name="doorOpen">DoorOpen 屬性的初始值。</param>
        public static tblSIte CreatetblSIte(global::System.Int32 sITE_ID, global::System.Boolean comm, global::System.Boolean aC, global::System.Boolean dC, global::System.Boolean amp, global::System.Boolean speaker, global::System.Boolean doorOpen)
        {
            tblSIte tblSIte = new tblSIte();
            tblSIte.SITE_ID = sITE_ID;
            tblSIte.Comm = comm;
            tblSIte.AC = aC;
            tblSIte.DC = dC;
            tblSIte.Amp = amp;
            tblSIte.Speaker = speaker;
            tblSIte.DoorOpen = doorOpen;
            return tblSIte;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SITE_ID
        {
            get
            {
                return _SITE_ID;
            }
            set
            {
                if (_SITE_ID != value)
                {
                    OnSITE_IDChanging(value);
                    ReportPropertyChanging("SITE_ID");
                    _SITE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SITE_ID");
                    OnSITE_IDChanged();
                }
            }
        }
        private global::System.Int32 _SITE_ID;
        partial void OnSITE_IDChanging(global::System.Int32 value);
        partial void OnSITE_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SITE_NAME
        {
            get
            {
                return _SITE_NAME;
            }
            set
            {
                OnSITE_NAMEChanging(value);
                ReportPropertyChanging("SITE_NAME");
                _SITE_NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SITE_NAME");
                OnSITE_NAMEChanged();
            }
        }
        private global::System.String _SITE_NAME;
        partial void OnSITE_NAMEChanging(global::System.String value);
        partial void OnSITE_NAMEChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Comm
        {
            get
            {
                return _Comm;
            }
            set
            {
                OnCommChanging(value);
                ReportPropertyChanging("Comm");
                _Comm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Comm");
                OnCommChanged();
            }
        }
        private global::System.Boolean _Comm;
        partial void OnCommChanging(global::System.Boolean value);
        partial void OnCommChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean AC
        {
            get
            {
                return _AC;
            }
            set
            {
                OnACChanging(value);
                ReportPropertyChanging("AC");
                _AC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AC");
                OnACChanged();
            }
        }
        private global::System.Boolean _AC;
        partial void OnACChanging(global::System.Boolean value);
        partial void OnACChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DC
        {
            get
            {
                return _DC;
            }
            set
            {
                OnDCChanging(value);
                ReportPropertyChanging("DC");
                _DC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DC");
                OnDCChanged();
            }
        }
        private global::System.Boolean _DC;
        partial void OnDCChanging(global::System.Boolean value);
        partial void OnDCChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Amp
        {
            get
            {
                return _Amp;
            }
            set
            {
                OnAmpChanging(value);
                ReportPropertyChanging("Amp");
                _Amp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Amp");
                OnAmpChanged();
            }
        }
        private global::System.Boolean _Amp;
        partial void OnAmpChanging(global::System.Boolean value);
        partial void OnAmpChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Speaker
        {
            get
            {
                return _Speaker;
            }
            set
            {
                OnSpeakerChanging(value);
                ReportPropertyChanging("Speaker");
                _Speaker = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Speaker");
                OnSpeakerChanged();
            }
        }
        private global::System.Boolean _Speaker;
        partial void OnSpeakerChanging(global::System.Boolean value);
        partial void OnSpeakerChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DoorOpen
        {
            get
            {
                return _DoorOpen;
            }
            set
            {
                OnDoorOpenChanging(value);
                ReportPropertyChanging("DoorOpen");
                _DoorOpen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DoorOpen");
                OnDoorOpenChanged();
            }
        }
        private global::System.Boolean _DoorOpen;
        partial void OnDoorOpenChanging(global::System.Boolean value);
        partial void OnDoorOpenChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BroadcastModel", Name="tblSysLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSysLog : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblSysLog 物件。
        /// </summary>
        /// <param name="id">ID 屬性的初始值。</param>
        /// <param name="sITE_ID">SITE_ID 屬性的初始值。</param>
        /// <param name="startTimeStamp">StartTimeStamp 屬性的初始值。</param>
        /// <param name="type">Type 屬性的初始值。</param>
        /// <param name="message">Message 屬性的初始值。</param>
        public static tblSysLog CreatetblSysLog(global::System.Int32 id, global::System.Int32 sITE_ID, global::System.DateTime startTimeStamp, global::System.String type, global::System.String message)
        {
            tblSysLog tblSysLog = new tblSysLog();
            tblSysLog.ID = id;
            tblSysLog.SITE_ID = sITE_ID;
            tblSysLog.StartTimeStamp = startTimeStamp;
            tblSysLog.Type = type;
            tblSysLog.Message = message;
            return tblSysLog;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SITE_ID
        {
            get
            {
                return _SITE_ID;
            }
            set
            {
                OnSITE_IDChanging(value);
                ReportPropertyChanging("SITE_ID");
                _SITE_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SITE_ID");
                OnSITE_IDChanged();
            }
        }
        private global::System.Int32 _SITE_ID;
        partial void OnSITE_IDChanging(global::System.Int32 value);
        partial void OnSITE_IDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime StartTimeStamp
        {
            get
            {
                return _StartTimeStamp;
            }
            set
            {
                OnStartTimeStampChanging(value);
                ReportPropertyChanging("StartTimeStamp");
                _StartTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTimeStamp");
                OnStartTimeStampChanged();
            }
        }
        private global::System.DateTime _StartTimeStamp;
        partial void OnStartTimeStampChanging(global::System.DateTime value);
        partial void OnStartTimeStampChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTimeStamp
        {
            get
            {
                return _EndTimeStamp;
            }
            set
            {
                OnEndTimeStampChanging(value);
                ReportPropertyChanging("EndTimeStamp");
                _EndTimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTimeStamp");
                OnEndTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTimeStamp;
        partial void OnEndTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeStampChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BroadcastModel", Name="tblUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUser : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblUser 物件。
        /// </summary>
        /// <param name="userID">UserID 屬性的初始值。</param>
        /// <param name="password">Password 屬性的初始值。</param>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        public static tblUser CreatetblUser(global::System.String userID, global::System.String password, global::System.Int32 groupID)
        {
            tblUser tblUser = new tblUser();
            tblUser.UserID = userID;
            tblUser.Password = password;
            tblUser.GroupID = groupID;
            return tblUser;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                if (_UserID != value)
                {
                    OnUserIDChanging(value);
                    ReportPropertyChanging("UserID");
                    _UserID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("UserID");
                    OnUserIDChanged();
                }
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                OnGroupIDChanging(value);
                ReportPropertyChanging("GroupID");
                _GroupID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GroupID");
                OnGroupIDChanged();
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// 沒有可用的中繼資料文件。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BroadcastModel", Name="tblUserGroup")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblUserGroup : EntityObject
    {
        #region Factory 方法
    
        /// <summary>
        /// 建立新 tblUserGroup 物件。
        /// </summary>
        /// <param name="groupID">GroupID 屬性的初始值。</param>
        /// <param name="groupName">GroupName 屬性的初始值。</param>
        public static tblUserGroup CreatetblUserGroup(global::System.Int32 groupID, global::System.String groupName)
        {
            tblUserGroup tblUserGroup = new tblUserGroup();
            tblUserGroup.GroupID = groupID;
            tblUserGroup.GroupName = groupName;
            return tblUserGroup;
        }

        #endregion

        #region 基本屬性
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 GroupID
        {
            get
            {
                return _GroupID;
            }
            set
            {
                if (_GroupID != value)
                {
                    OnGroupIDChanging(value);
                    ReportPropertyChanging("GroupID");
                    _GroupID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("GroupID");
                    OnGroupIDChanged();
                }
            }
        }
        private global::System.Int32 _GroupID;
        partial void OnGroupIDChanging(global::System.Int32 value);
        partial void OnGroupIDChanged();
    
        /// <summary>
        /// 沒有可用的中繼資料文件。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GroupName
        {
            get
            {
                return _GroupName;
            }
            set
            {
                OnGroupNameChanging(value);
                ReportPropertyChanging("GroupName");
                _GroupName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GroupName");
                OnGroupNameChanged();
            }
        }
        private global::System.String _GroupName;
        partial void OnGroupNameChanging(global::System.String value);
        partial void OnGroupNameChanged();

        #endregion

    
    }

    #endregion

    
}
