//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace winTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BroadcastEntities : DbContext
    {
        public BroadcastEntities()
            : base("name=BroadcastEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblApplication> tblApplication { get; set; }
        public DbSet<tblRecordSound> tblRecordSound { get; set; }
        public DbSet<tblSchedule> tblSchedule { get; set; }
        public DbSet<tblSIte> tblSIte { get; set; }
        public DbSet<tblSiteStatusLog> tblSiteStatusLog { get; set; }
        public DbSet<tblSysLog> tblSysLog { get; set; }
        public DbSet<tblTestLog> tblTestLog { get; set; }
        public DbSet<tblUser> tblUser { get; set; }
        public DbSet<tblUserGroup> tblUserGroup { get; set; }
    }
}
