//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace winTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestLog
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public int SITE_ID { get; set; }
        public bool AC { get; set; }
        public bool DC { get; set; }
        public bool AMP { get; set; }
        public bool SPK { get; set; }
        public bool DOOR { get; set; }
        public bool Comm { get; set; }
    }
}
